#!/bin/bash

pushd .. && \
PYTHONPATH=. python gfwlist2pac/main.py -i test/gfwlist.txt -f test/proxy.pac -p 'SOCKS5 127.0.0.1:1080' --user-rule test/user_rule.txt && \
PYTHONPATH=. python gfwlist2pac/main.py --precise -i test/gfwlist.txt -f test/proxy_abp.pac -p 'SOCKS5 127.0.0.1:1080' --user-rule test/user_rule.txt && \
popd && \
echo && \
echo 'Testing fast mode pac generated by gfwlist2pac' && \
cat proxy.pac performance_test.js > /tmp/test.js && \
node /tmp/test.js && \
echo && \
echo 'Testing precise mode pac generated by gfwlist2pac' && \
cat proxy_abp.pac performance_test.js > /tmp/test.js && \
node /tmp/test.js && \
echo && \
echo 'Testing pac generated by switchysharp' && \
cat switchysharp.pac performance_test.js > /tmp/test.js && \
node /tmp/test.js && \
echo && \
echo 'Test passed'
