language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs
  - pip install pep8 pyflakes coverage
script:
  - pep8 .
  - pyflakes .
  - cd test && ./test.sh
